### ISSUE TITLE
Bad mapping folder/user inside the container

### ISSUE THREAD

**Issue by hp48gx** [linuxserver/docker-syncthing#52]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

I use an asustor NAS. the official syncthing app uses this docker container under the hood.

the NAS filesystem looks as follows:
```
/volume1/Dir1 <== BTRFS
/volume2/Dir2 <== ext4
/share/Dir1 <== link to volume1/Dir1
/share/Dir2 <== link to volume2/Dir2
```

the container mounts `/share` as `/shared` for convenience, so you can add a shared folder to syncthing, but while `Dir1` works fine, trying to add `Dir2` gives permission errors.

```
2021-07-27 17:03:38: Failed to create folder marker: mkdir /shared/Dir2/.stfolder: permission denied
2021-07-27 17:03:38: Error on folder "Dir2" (lzwql-n6dn2): folder marker missing (this indicates potential data loss, search docs/forum to get information about how to proceed)
```

now, if I open a shell in the container, I see

```
root@98dab53da19e:/shared# ls -l
total 1
drwxrwxrwx 1 abc  ping  280 Apr 29 14:02 Dir1  
drwx------ 2 root root 1024 Jul 27 15:18 Dir2   
```

`ps aux`shows that syncthing in the container runs as user `abc`, so obviously it won't be able to use Dir2.

UPDATE:
1) it seems that the issue appears for every folder that is created while the container is running
2) a simple restart doesn't work
3) it seems that uninstalling _everything_ and reinstalling fixes the permissions.

Question: when _precisely_ the container sets the permission on Dir1, Dir2... ?

**Comment by sliterok** [comment]
Bump

**Comment by j0nnymoe** [comment]
Please could you provide all the information that was requested in the issue template.

**Comment by sliterok** [comment]
I'm not sure if my issue related but i guess it is

---
name: Bug report
about: Unable to create .stfolder without apparent reason for it.

---
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]





------------------------------

## Expected Behavior
Syncthing should create .stfolder for folders (inside volumes) that are specified in config

## Current Behavior
Throws error .stfolder marker missing

## Steps to Reproduce


1. Volume mounted inside docker-compose: [here](https://github.com/memolink/backend/blob/master/docker-compose.yml#L64)
2. Dockerfile setting up permissions for the folder in that volume: [here](https://github.com/memolink/backend/blob/master/Dockerfile#L6)
3. docker-compose up -d
4. get .stfolder marker missing error

## Environment
**OS:** win10
**CPU architecture:** x86_64
**How docker service was installed:** distro repo



## Command used to create docker container (run/create/compose/screenshot)

provided above

## Docker logs

[HPJFM] 08:16:47 INFO: Failed initial scan of receiveonly folder "example folder for memolink" (example-folder)
[HPJFM] 08:16:47 WARNING: Error on folder "example folder for memolink" (example-folder): folder marker missing (this indicates potential data loss, search docs/forum to get information about how to proceed)

## Additional notes
All permissions seem to be correct:
```
abc@6b90db171c48:/$ ls -l /sync
total 4
drwxr-xr-x 2 abc users 4096 Sep  8 20:12 example
```
Running `mkdir .stfolder` inside the container from user  `abc` fixes the issue. Files are received correctly, everything works fine

**Comment by hp48gx** [comment]
yes, it definitely seems related.

**Comment by Mastermjr** [comment]
for those that come across this. The folders you manually mount (-v HOSTFOLDER:/vol1/ )are not automatically chown to the correct container user "abc". 
You can fix this by `docker run syncthing chown -R abc /vol1`

hope this helps others!!

**Comment by sliterok** [comment]
Very good approach to the issues - add a bot that would remove them!
Why do people think that we need some sort of singularity and all-might AI to destroy out would if it could be done by the automation algorithms created by people, rather then something that is running ones and zeros.
