### ISSUE TITLE
[BUG] "syncthing cli operations shutdown" dont work

### ISSUE THREAD

**Issue by icf20** [linuxserver/docker-syncthing#71]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

root@1357e4230c1c:/# syncthing cli operations shutdown
unexpected HTTP status returned: 403 Forbidden
Forbidden
root@1357e4230c1c:/# 

### Expected Behavior

to stop syncthing

### Steps To Reproduce

send `syncthing cli operations shutdown` to the container

### Environment

```markdown
- OS:debian stable
- How docker service was installed: docker-compose
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "2.1"
services:
  syncthing:
    image: linuxserver/syncthing
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=100
      - TZ=why do you care?
    volumes:
      - why do you care?:/config
      - why do you care?:/data1
      - why do you care?:/data2
    ports:
      - why do you care?:8384
      - 22000:22000
      - 21027:21027/udp
    restart: unless-stopped
```

### Container logs

```bash
docker exec -it syncthing syncthing cli operations shutdown dont generate any logs
```

**Comment by homerr** [comment]
I'm going to close this off because;

- You asked why we need to know how you created your container... so we can replicate your setup to assist in debug
- You didn't detail the steps you went through to set up the cli
- Explain why you need this (if you stop synching, s6 will restart it)

Feel free to discuss further in discord as I feel that would be a better place for this subject.
